local/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect()->to('/login');
});

Auth::routes();

Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle')->name('auth-google');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback')->name('auth-google-callback');

Route::get('auth/logout', function(Request $requuest){
   \Illuminate\Support\Facades\Auth::logout();
   return redirect('login');
});

Route::middleware(['auth'])->group(function () {
    /*================ HOME ===================*/
    Route::prefix('home')->name('home.')->group(function () {
        Route::get('/', 'HomeController@index')->name('index');
    });

    /*================ BOLETINES ===================*/
    Route::prefix('boletines')->name('newsletters.')->group(function () {
        Route::get('/', 'BoletinesController@index')->middleware(['role:superadministrador|administrador|publicador'])->name('index');
        Route::get('nuevo', 'BoletinesController@create')->middleware(['role:superadministrador|administrador|publicador'])->name('create');
        Route::post('nuevo', 'BoletinesController@store')->middleware(['role:superadministrador|administrador|publicador'])->name('store');
        Route::get('{id}/editar', 'BoletinesController@edit')->middleware(['role:superadministrador|administrador|publicador'])->name('edit');
        Route::post('{id}/editar', 'BoletinesController@update')->middleware(['role:superadministrador|administrador|publicador'])->name('update');
        Route::get('{id}/visualizar', 'BoletinesController@preview')->middleware(['role:superadministrador|administrador|publicador'])->name('preview');
        Route::post('{id}/confirmar', 'BoletinesController@confirm')->middleware(['role:superadministrador|administrador'])->name('confirm');
        Route::post('{id}/anular', 'BoletinesController@cancel')->middleware(['role:superadministrador|administrador'])->name('cancel');

        /*================ NOTICIAS ===================*/
        Route::get('{boletin}/noticias', 'BoletinesController@news')->middleware(['role:superadministrador|administrador|publicador'])->name('news.index');
        Route::post('{boletin}/noticias/{id}/actualizar', 'BoletinesController@updateNew')->middleware(['role:superadministrador|administrador|publicador'])->name('news.update');
        Route::post('{boletin}/noticias/{id}/marcar-principal', 'BoletinesController@markFeaturedNew')->middleware(['role:superadministrador|administrador|publicador'])->name('news.mark-featured');
        Route::post('{boletin}/noticias/{id}/eliminar', 'BoletinesController@deleteNew')->middleware(['role:superadministrador|administrador|publicador'])->name('news.delete');

        /*================ CORREOS ===================*/
        Route::get('{boletin}/correos', 'BoletinesController@emails')->middleware(['role:superadministrador|administrador|publicador'])->name('emails.index');
        Route::post('{boletin}/correos/nuevo', 'BoletinesController@storeEmail')->middleware(['role:superadministrador|administrador|publicador'])->name('emails.store');
        Route::post('{boletin}/correos/{id}/eliminar', 'BoletinesController@deleteEmail')->middleware(['role:superadministrador|administrador|publicador'])->name('emails.delete');
    });

    /*================ PLANTILLAS ===================*/
    Route::prefix('plantillas')->middleware(['role:superadministrador|administrador'])->name('templates.')->group(function () {
        Route::get('/', 'PlantillasController@index')->name('index');
        Route::post('nuevo', 'PlantillasController@nuevo')->name('store');
        Route::post('editarAjax', 'PlantillasController@editarAjax')->name('edit');
        Route::post('editar', 'PlantillasController@editar')->name('update');
    });

    /*================ USUARIOS ===================*/
    Route::prefix('usuarios')->middleware(['role:superadministrador|administrador'])->name('users.')->group(function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::post('nuevo', 'UserController@nuevo')->name('store');
        Route::post('editarAjax', 'UserController@editarAjax')->name('edit');
        Route::post('editar', 'UserController@editar')->name('update');
    });

    /*================ LOGS ===================*/
    Route::prefix('logs')->name('logs.')->group(function () {
        Route::get('/', 'LogsController@index')->name('index');
    });

    /*BORRADO LOGICO*/
    Route::get('borrar/{id?}/{table?}', function($model, $id){
        if(auth()->user()->hasRole(['superadministrador', 'administrador'])) {        
            borradoLogico($model,$id);
            return redirect()->back()->with('message', 'Registro borrado correctamente')->with('messageType', 'success');
        } else {
            abort(403);
        }
    });
});

Route::get('comandos', function () {
    \Artisan::call('config:cache');
    \Artisan::call('config:clear');
    \Artisan::call('route:clear');
    \Artisan::call('view:clear');
    \Artisan::call('cache:clear');

    return "Comandos ejecutados correctamente";
});

local/app/Http/Controllers/BoletinesController.php
<?php

namespace App\Http\Controllers;

use App\Events\ConfirmNewsLetterEvent;
use Exception;
use App\Globals\Alerts;
use App\Globals\Constants;
use App\Imports\NewslettersEmailImport;
use App\Models\Boletin;
use App\Models\BoletinEstado;
use App\Models\BoletinNoticia;
use App\Models\Email;
use App\Models\Plantilla;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Maatwebsite\Excel\Facades\Excel;

class BoletinesController extends Controller
{
    public function __construct()
    {
        //code
    }

    public function index()
    {
        $boletines = Boletin::where('borrado_logico', '=', 0)->when(auth()->user()->hasRole(Constants::NAME_ROLE_PUBLISHER), function ($q) {
            return $q->where('user_id', auth()->user()->id);
        })->orderBy('id', 'DESC')->with(['estado', 'plantilla', 'user'])->get();

        return view('boletines.index', [
            'boletines' => $boletines
        ]);
    }

    public function create()
    {
        $plantillas = Plantilla::where('borrado_logico', '=', 0)->orderBy('id', 'ASC')->get();

        return view('boletines.create', [
            'plantillas' => $plantillas
        ]);
    }

    public function store(Request $request)
    {
        $data = $request->except(['_token']);
        $emailsList = [];

        if ($request->hasFile('file')) {

            try {

                DB::beginTransaction();

                $validator = Validator::make($request->all(), [
                    'nombre'      => 'required|string',
                    'descripcion' => 'nullable|string',
                    'asunto'      => 'required|string',
                    'plantilla'   => 'required|string',
                    'file'        => 'required|mimes:xlsx,xls'
                ]);

                if ($validator->fails()) {
                    return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
                }
            
                $rows = Excel::toArray(new NewslettersEmailImport, request()->file('file'));

                if(count($rows) > 0) {
                    foreach ($rows[0] as $email) {
                        if($email[0]) {
                            $emailsList[] = $email[0];
                        }
                    }
                }

                if (count($emailsList) === 0) {
                    $validator->getMessageBag()->add('Lista de Contactos', 'El archivo debe poseer al menos un mail para poder continuar');

                    return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
                }                

                $plantilla = Plantilla::where('slug', $data['plantilla'])->firstOrFail();
                $boletinEstadoPendiente = BoletinEstado::where('slug', Constants::NAME_STATUS_BULLETIN_PENDING)->firstOrFail();

                $boletin = Boletin::create([
                    'nombre'            => $data['nombre'],
                    'asunto'            => $data['asunto'],
                    'descripcion'       => $data['descripcion'],
                    'plantilla_id'      => $plantilla->id,
                    'boletin_estado_id' => $boletinEstadoPendiente->id,
                    'user_id'           => auth()->user()->id
                ]);

                foreach ($data['index'] as $index) {
                    BoletinNoticia::create([
                        'nombre'      => $data['titulos'][$index],
                        'descripcion' => $data['resumenes'][$index],
                        'enlace'      => $data['enlaces'][$index],
                        'path_imagen' => $data['imagenes'][$index],
                        'boletin_id'  => $boletin->id
                    ]);
                }

                foreach ($emailsList as $mail) {
                    $email = Email::firstOrCreate([
                        'email' => $mail
                    ], [
                        'borrado_logico' => 0
                    ]);

                    $boletin->emails()->attach($email);
                }

                DB::commit();

                return redirect()->route('newsletters.index')
                    ->with('message', Alerts::CREATE_SUCCESS)
                    ->with('messageType', 'success');

            } catch (Exception $e) {
                echo $e->getMessage();
                DB::rollback();
                return false;
            }
        }
    }

    public function edit($id)
    {
        $boletin = Boletin::with(['plantilla'])->findOrFail($id);

        if (auth()->user()->hasRole(Constants::NAME_ROLE_PUBLISHER)) {
            $this->authorize('passFilterNewsletter', $boletin);
        }

        $plantillas = Plantilla::where('borrado_logico', '=', 0)->orderBy('id', 'ASC')->get();

        return view('boletines.edit', [
            'boletin'    => $boletin,
            'plantillas' => $plantillas
        ]);
    }

    public function update($id, Request $request)
    {
        try {
            
            DB::beginTransaction();

            $data = $request->except(['_token', 'plantilla']);
            $boletin = Boletin::findOrFail($id);
            
            if (auth()->user()->hasRole(Constants::NAME_ROLE_PUBLISHER)) {
                $this->authorize('passFilterNewsletter', $boletin);
            }

            $validator = Validator::make($request->all(), [
                'nombre'      => 'required|string',
                'descripcion' => 'nullable|string',
                'asunto'      => 'required|string',
                'plantilla'   => 'required|string'
            ]);

            if ($validator->fails()) {
                return redirect()->back()
                    ->withErrors($validator)
                    ->withInput();
            }
                    
            $plantilla = Plantilla::where('slug', $request->post('plantilla'))->firstOrFail();
            $data['plantilla_id'] = $plantilla->id;

            $boletin->update($data);

            DB::commit();
            
            return redirect()->route('newsletters.index')
                ->with('message', Alerts::UPDATE_SUCCESS)
                ->with('messageType', 'success');

        } catch (Exception $e) {
            DB::rollback();
            return false;
        }
    }

    public function preview($id)
    {
        $boletin = Boletin::findOrFail($id);

        if (auth()->user()->hasRole(Constants::NAME_ROLE_PUBLISHER)) {
            $this->authorize('passFilterNewsletter', $boletin);
        }

        if(!empty($boletin->contenido)) {
            return $boletin->contenido;
        } else {
            $boletin->load(['plantilla', 'noticias']);            

            return view('emails.' . $boletin->plantilla->slug, [
                'boletin' => $boletin
            ]);
        }
    }

    public function confirm($id)
    {
        try {

            DB::beginTransaction();

            $boletin = Boletin::with(['plantilla', 'noticias'])->findOrFail($id);            
            $boletinEstadoAprobado = BoletinEstado::where('slug', Constants::NAME_STATUS_BULLETIN_APPROVED)->firstOrFail();

            $htmlBoletin = view('emails.' . $boletin->plantilla->slug, ['boletin' => $boletin])->render();

            Boletin::findOrFail($id)->update([
                'fecha_enviado'     => now(),
                'boletin_estado_id' => $boletinEstadoAprobado->id,
                'contenido'         => $htmlBoletin,                 
            ]);

            //event or jobs
            event(new ConfirmNewsLetterEvent($id));

            DB::commit();

            return redirect()->route('newsletters.index')
                ->with('message', Alerts::NEWSLETTER_CONFIRM)
                ->with('messageType', 'success');

        } catch (Exception $e) {
            DB::rollback();
            return false;
        }    
    }

    public function cancel($id)
    {
        try {

            DB::beginTransaction();

            $boletin = Boletin::findOrFail($id);

            if (auth()->user()->hasRole(Constants::NAME_ROLE_PUBLISHER)) {
                $this->authorize('passFilterNewsletter', $boletin);
            }

            $boletinEstadoAnulado = BoletinEstado::where('slug', Constants::NAME_STATUS_BULLETIN_CANCEL)->firstOrFail();

            $boletin->update([
                'boletin_estado_id' => $boletinEstadoAnulado->id
            ]);

            DB::commit();

            return redirect()->route('newsletters.index')
                ->with('message', Alerts::NEWSLETTER_CANCEL)
                ->with('messageType', 'success');
                
        } catch (Exception $e) {
            DB::rollback();
            return false;
        }
    }

    public function news($boletinId)
    {
        $boletin = Boletin::with(['noticias'])->findOrFail($boletinId);

        if (auth()->user()->hasRole(Constants::NAME_ROLE_PUBLISHER)) {
            $this->authorize('passFilterNewsletter', $boletin);
        }

        return view('boletines.news', [
            'boletin' => $boletin
        ]);
    }

    public function updateNew($boletinId, $id, Request $request)
    {
        $boletin = Boletin::findOrFail($boletinId);

        if (auth()->user()->hasRole(Constants::NAME_ROLE_PUBLISHER)) {
            $this->authorize('passFilterNewsletter', $boletin);
        }

        try {

            DB::beginTransaction();

            $data = $request->except(['_token']);
            $result = BoletinNoticia::where('id', $id)->update($data);

            DB::commit();
            
            return response()->json([
                'status'  => 'OK',
                'message' => Alerts::UPDATE_SUCCESS
            ]);

        } catch (Exception $e) {
            DB::rollback();

            return response()->json([
                'status'  => 'ERROR',

local/resources/views/boletines/index.blade.php
@extends('layouts.page')

@section('breadcrumb_content')
    <ol class="breadcrumb breadcrumb-alt float-right">
        <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Inicio</a></li>
        <li class="breadcrumb-item active">Boletines</li>
    </ol>
@endsection

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Boletines</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                </div>
                <div class="col-sm-6">
                    <div class="crud-button-list float-sm-right">
                        <a href="{{ route('newsletters.create') }}" class="btn btn-primary btn-flat btn-open-convocatoria-modal"><i class="fas fa-plus"></i>&nbsp;Nuevo</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body table-responsive">
                            <table id="example1" class="table table-bordered dataTable" role="grid" aria-describedby="example2_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">#ID</th>
                                        <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Nombre</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Asunto</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Plantilla</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Responsable</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Estado</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Creado</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Modificado</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($boletines as $boletin)
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">{{ $boletin->id }}</td>
                                            <td>{{ $boletin->nombre }}</td>
                                            <td>{{ $boletin->asunto }}</td>
                                            <td>{{ $boletin->plantilla->nombre }}</td>
                                            <td>{{ $boletin->user->name }}</td>
                                            <td>{{ $boletin->estado->nombre }}</td>   
                                            <td>{{ $boletin->created_at->format('d-m-Y') }}</td>
                                            <td>{{ $boletin->updated_at->format('d-m-Y') }}</td>
                                            <td class="text-center">
                                                <a href="{{ route('newsletters.preview', $boletin->id) }}" class="btn btn-default btn-sm btn-flat" title="Previsualizar" target="_blank">&nbsp;<i class="fas fa-eye"></i></a>
                                                                                                
                                                @if($boletin->estado->slug === Constants::NAME_STATUS_BULLETIN_PENDING)
                                                    <a href="{{ route('newsletters.edit', $boletin->id) }}" class="btn btn-default btn-sm btn-flat" title="Editar">&nbsp;<i class="fas fa-edit"></i></a>
                                                    <a href="{{ route('newsletters.news.index', $boletin->id) }}" class="btn btn-default btn-sm btn-flat" title="Listado de Noticias">&nbsp;<i class="fas fa-th-list"></i></a>

                                                    @role([Constants::NAME_ROLE_SUPERADMINISTRADOR, Constants::NAME_ROLE_ADMINISTRADOR])
                                                        <a href="{{ route('newsletters.confirm', $boletin->id) }}" class="btn btn-default btn-sm btn-flat btn-modal-post-confirmation" title="Confirmar y Enviar">&nbsp;<i class="fas fa-check-circle"></i></a>
                                                    @endrole
                                                @endif

                                                <a href="{{ route('newsletters.emails.index', $boletin->id) }}" class="btn btn-default btn-sm btn-flat" title="Listado de Correos">&nbsp;<i class="fas fa-mail-bulk"></i></a>

                                                @role([Constants::NAME_ROLE_SUPERADMINISTRADOR, Constants::NAME_ROLE_ADMINISTRADOR])
                                                    @if($boletin->estado->slug !== Constants::NAME_STATUS_BULLETIN_CANCEL)
                                                        <a href="{{ route('newsletters.cancel', $boletin->id) }}" class="btn btn-default btn-sm btn-flat btn-modal-post-confirmation" title="Anular">&nbsp;<i class="fas fa-ban"></i></a>
                                                    @endif

                                                    <a href="{{ url('borrar/boletin/' . $boletin->id) }}" class="btn btn-default btn-sm btn-flat btn-modal-confirmation" title="Eliminar">&nbsp;<i class="fas fa-trash"></i></a>
                                                @endrole
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">#ID</th>
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Nombre</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Asunto</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Plantilla</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Responsable</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Estado</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Creado</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Modificado</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Acciones</th>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

@section('script')

    <script>
        $('document').ready(function() {
            var table = $('.dataTable').DataTable({
                "responsive": true,
                "order": [[ 0, "desc" ]],
                "language": {
                    "url": "{{asset('Spanish.json')}}",
                }
            });
        });
    </script>

@endsection