local/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect()->to('/login');
});

Auth::routes();

Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle')->name('auth-google');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback')->name('auth-google-callback');

Route::get('auth/logout', function(Request $requuest){
   \Illuminate\Support\Facades\Auth::logout();
   return redirect('login');
});

Route::middleware(['auth'])->group(function () {
    /*================ HOME ===================*/
    Route::prefix('home')->name('home.')->group(function () {
        Route::get('/', 'HomeController@index')->name('index');
    });

    /*================ BOLETINES ===================*/
    Route::prefix('boletines')->name('newsletters.')->group(function () {
        Route::get('/', 'BoletinesController@index')->middleware(['role:superadministrador|administrador|publicador'])->name('index');
        Route::get('nuevo', 'BoletinesController@create')->middleware(['role:superadministrador|administrador|publicador'])->name('create');
        Route::post('nuevo', 'BoletinesController@store')->middleware(['role:superadministrador|administrador|publicador'])->name('store');
        Route::get('{id}/editar', 'BoletinesController@edit')->middleware(['role:superadministrador|administrador|publicador'])->name('edit');
        Route::post('{id}/editar', 'BoletinesController@update')->middleware(['role:superadministrador|administrador|publicador'])->name('update');
        Route::get('{id}/visualizar', 'BoletinesController@preview')->middleware(['role:superadministrador|administrador|publicador'])->name('preview');
        Route::post('{id}/confirmar', 'BoletinesController@confirm')->middleware(['role:superadministrador|administrador'])->name('confirm');
        Route::post('{id}/anular', 'BoletinesController@cancel')->middleware(['role:superadministrador|administrador'])->name('cancel');

        /*================ NOTICIAS ===================*/
        Route::get('{boletin}/noticias', 'BoletinesController@news')->middleware(['role:superadministrador|administrador|publicador'])->name('news.index');
        Route::post('{boletin}/noticias/{id}/actualizar', 'BoletinesController@updateNew')->middleware(['role:superadministrador|administrador|publicador'])->name('news.update');
        Route::post('{boletin}/noticias/{id}/marcar-principal', 'BoletinesController@markFeaturedNew')->middleware(['role:superadministrador|administrador|publicador'])->name('news.mark-featured');
        Route::post('{boletin}/noticias/{id}/eliminar', 'BoletinesController@deleteNew')->middleware(['role:superadministrador|administrador|publicador'])->name('news.delete');

        /*================ CORREOS ===================*/
        Route::get('{boletin}/correos', 'BoletinesController@emails')->middleware(['role:superadministrador|administrador|publicador'])->name('emails.index');
        Route::post('{boletin}/correos/nuevo', 'BoletinesController@storeEmail')->middleware(['role:superadministrador|administrador|publicador'])->name('emails.store');
        Route::post('{boletin}/correos/{id}/eliminar', 'BoletinesController@deleteEmail')->middleware(['role:superadministrador|administrador|publicador'])->name('emails.delete');
    });

    /*================ PLANTILLAS ===================*/
    Route::prefix('plantillas')->middleware(['role:superadministrador|administrador'])->name('templates.')->group(function () {
        Route::get('/', 'PlantillasController@index')->name('index');
        Route::post('nuevo', 'PlantillasController@nuevo')->name('store');
        Route::post('editarAjax', 'PlantillasController@editarAjax')->name('edit');
        Route::post('editar', 'PlantillasController@editar')->name('update');
    });

    /*================ USUARIOS ===================*/
    Route::prefix('usuarios')->middleware(['role:superadministrador|administrador'])->name('users.')->group(function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::post('nuevo', 'UserController@nuevo')->name('store');
        Route::post('editarAjax', 'UserController@editarAjax')->name('edit');
        Route::post('editar', 'UserController@editar')->name('update');
    });

    /*================ LOGS ===================*/
    Route::prefix('logs')->name('logs.')->group(function () {
        Route::get('/', 'LogsController@index')->name('index');
    });

    /*BORRADO LOGICO*/
    Route::get('borrar/{id?}/{table?}', function($model, $id){
        if(auth()->user()->hasRole(['superadministrador', 'administrador'])) {        
            borradoLogico($model,$id);
            return redirect()->back()->with('message', 'Registro borrado correctamente')->with('messageType', 'success');
        } else {
            abort(403);
        }
    });
});

Route::get('comandos', function () {
    \Artisan::call('config:cache');
    \Artisan::call('config:clear');
    \Artisan::call('route:clear');
    \Artisan::call('view:clear');
    \Artisan::call('cache:clear');

    return "Comandos ejecutados correctamente";
});

local/resources/views/partials/footer.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->


<form id="post-request-form" method="POST">
    @csrf
</form>

<!-- jQuery -->
<script src="{{ asset('adminlte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('adminlte/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('adminlte/dist/js/demo.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('adminlte/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script src="{{ asset('adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('adminlte/plugins/select2/js/select2.js') }}"></script>
<!-- SweetAlert2 -->
<script src="{{ asset('adminlte/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<!-- Multiselect -->
<script src="{{ asset('adminlte/plugins/multiselect/multi-select.js') }}"></script>
<!-- Jquery Validate -->
<script src="{{ asset('adminlte/plugins/jquery-validation/jquery.validate.min.js') }}"></script>
<script src="{{ asset('adminlte/plugins/jquery-validation/additional-methods.min.js') }}"></script>
<script src="{{ asset('adminlte/plugins/jquery-validation/localization/messages_es.min.js') }}"></script>
<script type="text/javascript">
	$(function() {
        $(document).on('click', '.btn-modal-confirmation', function(event) {
			
			event.preventDefault();
					
			var $link = $(this);
				
			Swal.fire({
				title: '¿Estás seguro que deseas borrar el registro seleccionado?',
				text: "¡No podrás revertir esto!",
				type: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#007bff',
				cancelButtonColor: '#dc3545',
				confirmButtonText: 'Confirmar',
				cancelButtonText: 'Cancelar'
			}).then((result) => {
				if (result.value) {
					$(location).attr('href', $link.attr('href'));
				}
			});            
		});

		$(document).on('click', '.btn-modal-post-confirmation', function(event) {
			event.preventDefault();
					
			var $link = $(this);
				
			Swal.fire({
				title: '¿Estás seguro que desea continuar con la acción seleccionada?',
				text: "¡No podrás revertir esto!",
				type: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#007bff',
				cancelButtonColor: '#dc3545',
				confirmButtonText: 'Confirmar',
				cancelButtonText: 'Cancelar'
			}).then((result) => {
				if (result.value) {
					$('#post-request-form').attr('action', $link.attr('href')).submit();
				}
			});
		});
	});
</script>

@if(session()->has('messageType'))
	@if(session()->get('messageType') == 'success')
	    <script>
            Swal.fire(
				'Acción Completada!',
				'{{ session()->get("message") }}',
				'success'
			);
	    </script>
	@elseif(session()->get('messageType') == 'error')
	    <script>
			Swal.fire(
				'Acción no completada!',
				'{{ session()->get("message") }}',
				'error'
			);
	    </script>
	@endif
@endif

</body>
</html>

local/resources/views/partials/header.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">    
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@yield('title,', 'Boletines')</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/fontawesome-free/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/select2/css/select2.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('adminlte/dist/css/adminlte.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/sweetalert2/sweetalert2.min.css') }}">
    <!-- Multiselect -->
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/multiselect/multi-select.css') }}">

    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <!-- Google Font: Source Sans Pro -->
    <!--<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">-->

    <style>
        .custom-header {
            min-height: 80px;
            background-color:#8c1919;
            border-bottom: 3px solid #FFB800;
        }
        
        .layout-navbar-fixed .wrapper .main-header {
            position: relative !important;
        }

        .layout-navbar-fixed .wrapper .brand-link {
            position: relative !important;
        }

        .layout-navbar-fixed .wrapper .content-wrapper {
            margin-top: 0 !important;
        }

        .custom-header #header-logo img {
            max-height: 100px !important;
        }

        .breadcrumb-alt {
            background-color: #fff;
            padding: .5rem 1rem;
            margin-top: .75rem;
        }

        .tabla-convocatorias td {
            padding: 0.35rem !important;
        }

        .text-truncate {
            max-width: 150px;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
        }

        .table-alt th {
            text-align: center;
        }

        @media screen and (min-width: 1600px) {
            .text-truncate {
                max-width: 400px;
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;
            }   
        }
    </style>

    @yield('styles')
</head>
<body class="hold-transition sidebar-mini layout-navbar-fixed">
    <header class="custom-header">
        <nav class="navbar navbar-expand">
            <div class="container-fluid p-1">
                <div class="col-6 col-sm-6 col-md-4">
                    <div id="header-logo">
                        <a href="{{ route('home.index') }}">
                            <img src="{{ asset('img/logo.png') }}" alt="" class="img-fluid img-responsive">
                        </a>
                    </div>
                </div>
                <div class="col-6 col-lg-7">
                    <div class="row float-right">
                        <div class="col-xs-12">
                            <a href="{{ url('auth/logout') }}" class="btn btn-danger nav-link mb-2"><i class="fas fa-sign-out-alt"></i>&nbsp;Cerrar Sesión</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <!-- Site wrapper -->
    <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <div class="col-4 col-sm-6">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
        </div>
        <div class="col-8 col-sm-6">
            @yield('breadcrumb_content', '')
        </div>
    </nav>
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{{ route('home.index') }}" class="brand-link elevation-4">
            <img src="{{ auth()->user()->avatar }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light"> {{ auth()->user()->name }} </span>
        </a>
        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-item {{ request()->routeIs('newsletters.*') ? 'menu-open' : null }}">
                        <a href="{{ route('newsletters.index') }}" class="nav-link">
                            <i class="nav-icon fas fa-newspaper"></i>
                            <p>
                                Boletines
                            </p>
                        </a>
                    </li>                    

                    @role([Constants::NAME_ROLE_SUPERADMINISTRADOR, Constants::NAME_ROLE_ADMINISTRADOR])
                        <li class="nav-item {{ request()->routeIs('templates.*') ? 'menu-open' : null }}">
                            <a href="{{ route('templates.index') }}" class="nav-link">
                                <i class="nav-icon fas fa-file"></i>
                                <p>
                                    Plantillas
                                </p>
                            </a>
                        </li>
                        <li class="nav-item {{ request()->routeIs('users.*') ? 'menu-open' : null }}">
                            <a href="{{ route('users.index') }}" class="nav-link">
                                <i class="nav-icon fas fa-user"></i>
                                <p>
                                    Usuarios
                                </p>
                            </a>
                        </li>
                    @endrole                    
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>