local/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect()->to('/login');
});

Auth::routes();

Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle')->name('auth-google');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback')->name('auth-google-callback');

Route::get('auth/logout', function(Request $requuest){
   \Illuminate\Support\Facades\Auth::logout();
   return redirect('login');
});

Route::middleware(['auth'])->group(function () {
    /*================ HOME ===================*/
    Route::prefix('home')->name('home.')->group(function () {
        Route::get('/', 'HomeController@index')->name('index');
    });

    /*================ BOLETINES ===================*/
    Route::prefix('boletines')->name('newsletters.')->group(function () {
        Route::get('/', 'BoletinesController@index')->middleware(['role:superadministrador|administrador|publicador'])->name('index');
        Route::get('nuevo', 'BoletinesController@create')->middleware(['role:superadministrador|administrador|publicador'])->name('create');
        Route::post('nuevo', 'BoletinesController@store')->middleware(['role:superadministrador|administrador|publicador'])->name('store');
        Route::get('{id}/editar', 'BoletinesController@edit')->middleware(['role:superadministrador|administrador|publicador'])->name('edit');
        Route::post('{id}/editar', 'BoletinesController@update')->middleware(['role:superadministrador|administrador|publicador'])->name('update');
        Route::get('{id}/visualizar', 'BoletinesController@preview')->middleware(['role:superadministrador|administrador|publicador'])->name('preview');
        Route::post('{id}/confirmar', 'BoletinesController@confirm')->middleware(['role:superadministrador|administrador'])->name('confirm');
        Route::post('{id}/anular', 'BoletinesController@cancel')->middleware(['role:superadministrador|administrador'])->name('cancel');

        /*================ NOTICIAS ===================*/
        Route::get('{boletin}/noticias', 'BoletinesController@news')->middleware(['role:superadministrador|administrador|publicador'])->name('news.index');
        Route::post('{boletin}/noticias/{id}/actualizar', 'BoletinesController@updateNew')->middleware(['role:superadministrador|administrador|publicador'])->name('news.update');
        Route::post('{boletin}/noticias/{id}/marcar-principal', 'BoletinesController@markFeaturedNew')->middleware(['role:superadministrador|administrador|publicador'])->name('news.mark-featured');
        Route::post('{boletin}/noticias/{id}/eliminar', 'BoletinesController@deleteNew')->middleware(['role:superadministrador|administrador|publicador'])->name('news.delete');

        /*================ CORREOS ===================*/
        Route::get('{boletin}/correos', 'BoletinesController@emails')->middleware(['role:superadministrador|administrador|publicador'])->name('emails.index');
        Route::post('{boletin}/correos/nuevo', 'BoletinesController@storeEmail')->middleware(['role:superadministrador|administrador|publicador'])->name('emails.store');
        Route::post('{boletin}/correos/{id}/eliminar', 'BoletinesController@deleteEmail')->middleware(['role:superadministrador|administrador|publicador'])->name('emails.delete');
    });

    /*================ PLANTILLAS ===================*/
    Route::prefix('plantillas')->middleware(['role:superadministrador|administrador'])->name('templates.')->group(function () {
        Route::get('/', 'PlantillasController@index')->name('index');
        Route::post('nuevo', 'PlantillasController@nuevo')->name('store');
        Route::post('editarAjax', 'PlantillasController@editarAjax')->name('edit');
        Route::post('editar', 'PlantillasController@editar')->name('update');
    });

    /*================ USUARIOS ===================*/
    Route::prefix('usuarios')->middleware(['role:superadministrador|administrador'])->name('users.')->group(function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::post('nuevo', 'UserController@nuevo')->name('store');
        Route::post('editarAjax', 'UserController@editarAjax')->name('edit');
        Route::post('editar', 'UserController@editar')->name('update');
    });

    /*================ LOGS ===================*/
    Route::prefix('logs')->name('logs.')->group(function () {
        Route::get('/', 'LogsController@index')->name('index');
    });

    /*BORRADO LOGICO*/
    Route::get('borrar/{id?}/{table?}', function($model, $id){
        if(auth()->user()->hasRole(['superadministrador', 'administrador'])) {        
            borradoLogico($model,$id);
            return redirect()->back()->with('message', 'Registro borrado correctamente')->with('messageType', 'success');
        } else {
            abort(403);
        }
    });
});

Route::get('comandos', function () {
    \Artisan::call('config:cache');
    \Artisan::call('config:clear');
    \Artisan::call('route:clear');
    \Artisan::call('view:clear');
    \Artisan::call('cache:clear');

    return "Comandos ejecutados correctamente";
});

local/app/Models/Plantilla.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Plantilla extends Model
{
    use Sluggable;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'plantilla';

    protected $fillable = [
        'slug', 'nombre', 'descripcion', 'path_imagen', 'estado'
    ];

    protected $dates = [
        'created_at', 'updated_at'
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'nombre',
                'onUpdate' => true
            ]
        ];
    }

    public function boletinesPlantilla()
    {
        return $this->hasMany(\App\Models\Boletin::class, 'plantilla_id');
    }

    public function getStatus()
    {
        return ($this->estado) ? 'Activo' : 'Suspendido';
    }
}

local/app/Http/Controllers/PlantillasController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Globals\Alerts;
use App\Http\Controllers\Logs\CreateLogsController;
use App\Models\Plantilla;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class PlantillasController extends Controller
{
    public function __construct()
    {
        //code
    }

    public function index()
    {
        $plantillas = Plantilla::where('borrado_logico', '=', 0)->orderBy('id', 'ASC')->get();

        return view('plantillas.index', [
            'plantillas' => $plantillas,
        ]);
    }

    public function nuevo(Request $request)
    {
        if ($request->isMethod('post')) {
            try {

                DB::beginTransaction();

                $plantilla = new Plantilla;
                $plantilla->nombre = $request->post('nombre');
                $plantilla->descripcion = $request->post('descripcion');
                $plantilla->estado = $request->post('estado');
                $plantilla->save();

                //CreateLogsController::newUserLog($plantilla, 'INSERT');

                DB::commit();

                return redirect()->route('templates.index')
                    ->with('message', Alerts::CREATE_SUCCESS)
                    ->with('messageType', 'success');
                
            } catch (Exception $e) {
                DB::rollback();
                return false;
            }
        }
    }

    public function editarAjax(Request $request)
    {
        if ($request->ajax()) {
            $plantilla = Plantilla::findOrFail($request->get('plantillaId'));

            return response()->json($plantilla);
        } else {
            return abort(404);
        }
    }

    public function editar(Request $request)
    {
        if ($request->method('post')) {

            try {

                DB::beginTransaction();

                $plantilla = Plantilla::findOrFail($request->get('plantilla_id'));

                $plantilla->descripcion = $request->post('edit-descripcion');
                $plantilla->estado = $request->post('edit-estado');

                if ($request->hasFile('edit-image') && $request->file('edit-image')->isValid()) {
                    $file = $request->file('edit-image');
                    $filename = $plantilla->slug . '.' . $file->getClientOriginalExtension();

                    Storage::disk('public')->putFileAs('plantillas', $file, $filename);

                    $plantilla->path_imagen = $filename;
                }

                $plantilla->save();

                DB::commit();

                return redirect()->route('templates.index')
                    ->with('message', Alerts::UPDATE_SUCCESS)
                    ->with('messageType', 'success');

            } catch (Exception $e) {
                DB::rollback();
                return false;
            }
        } else {
            return abort(404);
        }
    }
}

local/resources/views/plantillas/index.blade.php
@extends('layouts.page')

@section('breadcrumb_content')
    <ol class="breadcrumb breadcrumb-alt float-right">
        <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Inicio</a></li>
        <li class="breadcrumb-item active">Plantillas</li>
    </ol>
@endsection

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Plantillas</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    &nbsp;
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body table-responsive">
                            <table id="example1" class="table table-bordered dataTable" role="grid" aria-describedby="example2_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column ascending">#ID</th>
                                        <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column ascending">Nombre</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Descripción</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Imagen Referencial</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Estado</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Creado</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($plantillas as $plantilla)
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">{{ $plantilla->id }}</td>
                                            <td>{{ $plantilla->nombre }}</td>
                                            <td>{{ $plantilla->descripcion }}</td>

                                            @if(!empty($plantilla->path_imagen))
                                                <td>
                                                    <a href="{{ asset('local/public/plantillas/' . $plantilla->path_imagen) }}" target="_blank">Ver Imagen</a>
                                                </td>
                                            @else
                                                <td>&nbsp;</td>
                                            @endif

                                            @if($plantilla->estado === 1)
                                                <td><label for="" class="badge badge-success">ACTIVO</label></td>
                                            @else
                                                <td><label for="" class="badge badge-danger">INACTIVO</label></td>
                                            @endif

                                            <td>{{ $plantilla->created_at->format('d-m-Y') }}</td>
                                            
                                            <td class="text-center">
                                                <button class="btn btn-default btn-sm btn-flat" id="btn-edit" onclick="editarPlantilla({{ $plantilla->id }})"><i class="fas fa-edit"></i></button>
                                                <a class="btn btn-default btn-sm btn-flat btn-modal-confirmation d-none" id="btn-delete" href="{{ url('borrar/plantilla/' . $plantilla->id) }}"><i class="fas fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column ascending">#ID</th>
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column ascending">Nombre</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Descripción</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Imagen Referencial</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Estado</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Creado</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Acciones</th>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--EDITAR PLANTILLA MODAL-->
    <div class="modal fade" tabindex="-1" role="dialog" id="editar-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Editar Plantilla</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form role="form" name="nueva" method="post" action="{{ route('templates.update') }}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="modal-body">                
                        <input type="hidden" name="plantilla_id" id="plantilla_id">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="edit-nombre">Nombre(*)</label>
                                <input type="text" class="form-control" name="edit-nombre" id="edit-nombre" readonly="readonly" required="required">
                            </div>
                            <div class="form-group">
                                <label for="edit-descripcion">Descripción(*)</label>
                                <textarea type="text" class="form-control" name="edit-descripcion" id="edit-descripcion"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="edit-image">Imagen Referencial(*)</label>
                                <input type="file" name="edit-image" id="edit-image" accept="image/*">
                            </div>
                            <div class="form-group">
                                <label for="edit-estado">Estatus(*)</label>
                                <select name="edit-estado" id="edit-estado" class="form-control" required="required">
                                    <option value="1">ACTIVO</option>
                                    <option value="0">INACTIVO</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary btn-sm btn-flat"><i class="fas fa-save"></i>&nbsp;Guardar</button>
                        <button type="button" class="btn btn-danger btn-sm btn-flat" data-dismiss="modal">&nbsp;Cerrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--/ EDITAR USUARIO-->

@endsection

@section('script')
    <script>
        function editarPlantilla(plantillaId) 
        {
            var $editarModal = $('#editar-modal');

            $.ajax({
                type:'post',
                data: { plantillaId: plantillaId, _token: '{{csrf_token()}}'},
                dataType: 'json',
                url: '{{ route("templates.edit") }}',
                complete: function(data){
                    var plantilla = data.responseJSON;

                    $editarModal.find('#plantilla_id').val(plantillaId);
                    $editarModal.find('#edit-nombre').val(plantilla.nombre);
                    $editarModal.find('#edit-descripcion').text(plantilla.descripcion);
                    $editarModal.find('#edit-estado').val(plantilla.estado).trigger('change');

                    $editarModal.modal('show');
                }
            });
        }

        $('document').ready(function() {
            var table = $('.dataTable').DataTable({
                "responsive": true,
                "order": [[ 0, "asc" ]],
                "language": {
                    "url": "{{asset('Spanish.json')}}",
                }
            });

            $('.btn-open-convocatoria-modal').on('click', function(event) {
                event.preventDefault();

                var $convocatoriaModal = $('#convocatoria-modal'); 

                //Clean Form
                $convocatoriaModal.find('input').val('');
                $convocatoriaModal.find('select').prop("selectedIndex", 0);

                //Open Modal
                $convocatoriaModal.modal('show');
            });

            $('#convocatoria-modal form').on('submit', function(event) {                            
                var $form = $(this);
                    
                $form.append('{{csrf_field()}}');
            });
        });
    </script>

@endsection